### ISSUE TITLE
Is theLortex a human?

### ISSUE THREAD

**Issue by maiste** [TheLortex/githereum#11]
We don't have any proof of it as he did not open a PR to prove his own existence.

**Comment by TheLortex** [comment]
Hi, thank you for your issue raising serious concerns in the Blockchain Ecosystem.
 
I will now prove that I am indeed human.

Claim 1: here is a photo I have taken of a Raspberry Pi computer.

![IMG_20220401_151041](https://user-images.githubusercontent.com/966015/161270418-0a8fe0b4-8a43-4470-9e8d-90c4ab315321.jpg)

Fact: I cannot be this Raspberry Pi computer. Indeed computers cannot take selfies. 

Other fact: only two _Things_ can interact with the _Internet_: _humans_ and _computers_.

Conclusion: As I am not the Raspberry Pi computer, it is obvious that I am a human.

**Comment by maiste** [comment]
As a Human, I can't compete with such logic. So maybe you are a computer. However, fact 1 is a valid answer. You are accepted as a human.
