### ISSUE TITLE
Proof of existence

### ISSUE THREAD

**Issue by MisterDA** [TheLortex/githereum#12]
![caml-existentialiste](https://user-images.githubusercontent.com/1773581/161271470-46721bbc-0617-431c-85a8-5a7569944cee.png)

This camel is obviously so bad it cannot have been drawn by a robot.
Or was it?

ref #7 
cc @TheLortex @maiste

**Comment by TheLortex** [comment]
Existence is confirmed. Thank you, I will now populate your user account with 10 Gitcoins, then we will validate the transaction.

**Comment by MisterDA** [comment]
Note that if my existence isn't recognized I will hard-fork the blockchain.

**Comment by maiste** [comment]
Only Paint can compete with this: you are a human.
