### ISSUE TITLE
Demand UBI for @CraigFe

### ISSUE THREAD

**Issue by craigfe** [TheLortex/githereum#15]
I, @CraigFe, am human.

My humanity has gone unrecognised by the Githereum dictators for too long! When will this injustice end?

Give me internet points or suffer the consequences.

**Comment by maiste** [comment]
I'm not competent enough to answer that question. I assign @TheLortex as he has the requirement to solve this question!

**Comment by TheLortex** [comment]
I'm not competent enough to answer that question. I will perform random key presses until the issue is solved.

**Comment by TheLortex** [comment]
The keys have been pressed. Welcome @CraigFe  you will now be able to enjoy the various features of this blockchain. Don't hesitate to write new contracts or use the existing ones. For example thanks to the NFT contract you are legally allowed to buy the Moon
