### ISSUE TITLE
Request 10 Gitcoins

### ISSUE THREAD

**Issue by maiste** [TheLortex/githereum#4]
Dear @TheLortex wonderful maintainer,
I'm @maiste and the PR is here to tell you that I exist (following the Githereum protocol). Could I get the 10 gitcoins related to my existence?
Respectfully,
Maiste.

**Comment by TheLortex** [comment]
Hi @maiste. Please prove your existence as an human by answering this CAPTCHA:

What kind of bear is best ?

**Comment by maiste** [comment]
That's a ridiculous question!
However, I would say the right answer is `Black bear`
